name: lint-code


on:
  push:
    branches:
      - master
jobs:
  code_quality:
    name: Code Quality
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.31.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: golangci-lint
        run: |
          golangci-lint run